# Generated by Django 4.0.6 on 2022-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='credit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
