# Generated by Django 4.0.6 on 2022-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_created_page_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
