# Generated by Django 4.0.6 on 2022-08-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_content_en_page_subtitle_en_page_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(blank=True),
        ),
    ]
